export const MOCK_DASHBOARD = {
  stats: {
    totalTours: 2,
    totalHotels: 2,
    approvedTours: 2,
    approvedHotels: 2,
    pendingTours: 0,
    pendingHotels: 0,
    totalBookings: 6,
    upcomingBookings: 4,
    completedBookings: 1,
    tourBookings: 3,
    hotelBookings: 3,
    totalTravelers: 11,
    totalRoomNights: 12,
    tourRevenue: 14497.5,
    hotelRevenue: 36600,
    totalRevenue: 51097.5,
  },
  recentBookings: [
    {
      _id: "m1",
      type: "hotel",
      customerName: "Rahul Sharma",
      customerPhone: "9988776655",
      listingTitle: "Seaside Villa Resort",
      listingLocation: "Goa",
      checkIn: new Date(Date.now() + 7 * 86400000).toISOString(),
      checkOut: new Date(Date.now() + 10 * 86400000).toISOString(),
      rooms: 2,
      guests: 4,
      roomType: "Sea View Deluxe",
      paidAmount: 13500,
      totalAmount: 13500,
      bookingStatus: "Confirmed",
      bookedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      _id: "m2",
      type: "tour",
      customerName: "Rahul Sharma",
      customerPhone: "9988776655",
      listingTitle: "Goa Beach Escape",
      listingLocation: "Goa",
      startDate: new Date(Date.now() + 12 * 86400000).toISOString(),
      endDate: new Date(Date.now() + 16 * 86400000).toISOString(),
      travelers: 2,
      children: 1,
      room: "Deluxe",
      paidAmount: 4250,
      totalAmount: 42500,
      bookingStatus: "Confirmed",
      bookedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    },
    {
      _id: "m3",
      type: "hotel",
      customerName: "Priya Patel",
      customerPhone: "9876512340",
      listingTitle: "Hilltop Homestay",
      listingLocation: "Manali",
      checkIn: new Date(Date.now() + 14 * 86400000).toISOString(),
      checkOut: new Date(Date.now() + 17 * 86400000).toISOString(),
      rooms: 1,
      guests: 2,
      roomType: "Mountain View",
      paidAmount: 9600,
      totalAmount: 9600,
      bookingStatus: "Confirmed",
      bookedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    },
  ],
  upcomingBookings: [],
  activity: [
    {
      id: "a1",
      type: "hotel_booking",
      title: "Rahul Sharma booked 2 room(s) at Seaside Villa Resort",
      subtitle: "Sea View Deluxe · Check-in in 7 days",
      amount: 13500,
      status: "Confirmed",
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      icon: "bed",
    },
    {
      id: "a2",
      type: "tour_booking",
      title: "Rahul Sharma booked Goa Beach Escape",
      subtitle: "2 travelers + 1 child · Trip in 12 days",
      amount: 4250,
      status: "Confirmed",
      timestamp: new Date(Date.now() - 2 * 86400000).toISOString(),
      icon: "airplane",
    },
    {
      id: "a3",
      type: "hotel_booking",
      title: "Priya Patel booked 1 room(s) at Hilltop Homestay",
      subtitle: "Mountain View · 14 Jul – 17 Jul",
      amount: 9600,
      status: "Confirmed",
      timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
      icon: "bed",
    },
    {
      id: "a4",
      type: "tour_booking",
      title: "Priya Patel booked Manali Snow Trek",
      subtitle: "4 travelers · Trip in 25 days",
      amount: 7560,
      status: "Confirmed",
      timestamp: new Date(Date.now() - 5 * 86400000).toISOString(),
      icon: "airplane",
    },
    {
      id: "a5",
      type: "tour_booking",
      title: "Amit Singh completed Goa Beach Escape",
      subtitle: "2 travelers · Completed last month",
      amount: 2687.5,
      status: "Confirmed",
      timestamp: new Date(Date.now() - 30 * 86400000).toISOString(),
      icon: "airplane",
    },
  ],
  recentTours: [],
  recentHotels: [],
};

const MOCK_BOOKINGS_ALL = [
  ...MOCK_DASHBOARD.recentBookings,
  {
    _id: "m4",
    type: "tour" as const,
    customerName: "Priya Patel",
    customerPhone: "9876512340",
    listingTitle: "Manali Snow Trek",
    listingLocation: "Manali",
    startDate: new Date(Date.now() + 25 * 86400000).toISOString(),
    endDate: new Date(Date.now() + 30 * 86400000).toISOString(),
    travelers: 4,
    children: 0,
    paidAmount: 7560,
    totalAmount: 75600,
    bookingStatus: "Confirmed",
    bookedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    _id: "m5",
    type: "hotel" as const,
    customerName: "Amit Singh",
    customerPhone: "9123456780",
    listingTitle: "Seaside Villa Resort",
    listingLocation: "Goa",
    checkIn: new Date(Date.now() - 10 * 86400000).toISOString(),
    checkOut: new Date(Date.now() - 7 * 86400000).toISOString(),
    rooms: 1,
    guests: 2,
    roomType: "Standard",
    paidAmount: 13500,
    totalAmount: 13500,
    bookingStatus: "Completed",
    bookedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const MOCK_BOOKINGS = {
  all: MOCK_BOOKINGS_ALL,
  upcoming: MOCK_BOOKINGS_ALL.filter((b) => b.bookingStatus === "Confirmed"),
  past: MOCK_BOOKINGS_ALL.filter((b) => b.bookingStatus === "Completed"),
  completed: MOCK_BOOKINGS_ALL.filter((b) => b.bookingStatus === "Completed"),
  tourBookings: MOCK_BOOKINGS_ALL.filter((b) => b.type === "tour"),
  hotelBookings: MOCK_BOOKINGS_ALL.filter((b) => b.type === "hotel"),
};